# A single CI script with github workflow
name: Build wheels

on:
  push:
  release:
    types:
      - published

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12"]
    uses: qiboteam/workflows/.github/workflows/deploy-pip-poetry.yml@v1
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      publish: ${{ github.event_name == 'release' && github.event.action == 'published' && matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9' }}
      poetry-extras: "--with docs,tests,analysis"
    secrets: inherit
